package ru.chabanov;

public enum COMMAND {
    DELETE_ON_SERVER,
    DELETE_ON_CLIENT,
    SEND_TO_SERVER,
    SEND_TO_CLIENT,
    SHOW_ON_SERVER,
    SHOW_ON_SERVER_ONLY_NAME,
    CHECK_AUTH,
    RESPONSE_AUTH,
    CLIENT_IS_AUTH,
    EMPTY_COMMAND;
}
